### ISSUE TITLE
automic dependency java protoc

### ISSUE THREAD

**Issue by LoranceChen** [sbt/sbt-protobuf#134] opened 2022-12-01 05:34 UTC
For generate service stub, must setting protoc-gen-grpc-java setting which need refers to local path. 
```
    ProtobufConfig / protobufProtocOptions ++= Seq(
      "--plugin=protoc-gen-grpc-java=" + PATH_GRPC_JAVA_PLUGIN,
      "--grpc-java_out=" + baseDirectory.value + "/target/scala-2.13/src_managed/main/compiled_protobuf"
    ),
```
Hope detect gprc language from maven central automaticly.

**Comment by eed3si9n** [comment] 2024-03-05 17:24
Closing this as a duplicate of #31

**Closed by eed3si9n** 2024-03-05 17:24 UTC
